scoring-base: 'http://crawl.akrasiac.org'

sources:
  - name: cao
    base: http://crawl.akrasiac.org

    # If the file exists in this path, it will be linked into the data
    # directory from the local path; otherwise it will be fetched
    # using http.
    local: /var/www
    logfiles:
      - allgames.txt
      - logfile04
      - logfile05
      - logfile06
      - logfile07
      - logfile08
      - logfile09
      - logfile10
      - logfile11
      - logfile-git
    milestones:
      - milestones02
      - milestones03
      - milestones04
      - milestones05
      - milestones06
      - milestones07
      - milestones08
      - milestones09
      - milestones10
      - milestones11
      - milestones-git

    # Regex -> location; player name is automatically appended.
    morgues:
      - http://crawl.akrasiac.org/rawdata

  - name: cdo
    base: http://crawl.develz.org
    logfiles:
      - allgames-0.4.txt
      - allgames-0.5.txt
      - allgames-0.6.txt
      - allgames-0.7.txt
      - allgames-0.8.txt
      - allgames-0.10.txt
      - allgames-0.11.txt
      - allgames-svn.txt
    milestones:
      - milestones-0.6.txt
      - milestones-0.7.txt
      - milestones-0.8.txt
      - milestones-0.10.txt
      - milestones-0.11.txt
      - milestones-svn.txt
    morgues:
      - - time_gt: ['end_time', '20110819-1740']
          version_match: ['v', '0.9']
        - http://crawl.develz.org/morgues/0.9
      - ['cdo.*-(?:svn)', 'http://crawl.develz.org/morgues/trunk']
      - ['cdo.*-(.*)$', 'http://crawl.develz.org/morgues/$1']

  - name: cszo
    base: http://dobrazupa.org
    logfiles:
      - meta/git/logfile
      - meta/0.12/logfile
      - meta/0.11/logfile
      - meta/0.10/logfile
    milestones:
      - meta/git/milestones
      - meta/0.12/milestones
      - meta/0.11/milestones
      - meta/0.10/milestones
    morgues:
      - http://dobrazupa.org/morgue

  - name: csn
    base: http://crawlus.somatika.net
    logfiles: {}
    milestones: {}
    morgues:
      - http://crawlus.somatika.net/dumps
