sources:
  - name: cao
    # If the file exists in this path, it will be linked into the data
    # directory from the local path; otherwise it will be fetched
    # using http.
    base: http://crawl.akrasiac.org
    local: /var/www/crawl
    logfiles:
      - allgames.txt
      - logfile04
      - logfile05
      - logfile06
      - logfile07
      - logfile08
      - logfile09
      - logfile10
      - logfile11
      - logfilegit
    milestones:
      - milestones02.txt
      - milestones03.txt
      - milestones04.txt
      - milestones05.txt
      - milestones06.txt
      - milestones07.txt
      - milestones08.txt
      - milestones09.txt
      - milestones10.txt
      - milestones11.txt
      - milestones-git

  - name: cdo
    base: http://crawl.develz.org
    logfiles:
      - allgames-0.4.txt
      - allgames-0.5.txt
      - allgames-0.6.txt
      - allgames-0.7.txt
      - allgames-0.8.txt
      - allgames-0.10.txt
      - allgames-0.11.txt
      - allgames-svn.txt
    milestones:
      - milestones-0.6.txt
      - milestones-0.7.txt
      - milestones-0.8.txt
      - milestones-0.10.txt
      - milestones-0.11.txt
      - milestones-svn.txt

  - name: cszo
    base: http://dobrazupa.org
    logfiles:
      - meta/git/logfile
      - meta/0.11/logfile
      - meta/0.10/logfile
    milestones:
      - meta/git/milestones
      - meta/0.11/milestones
      - meta/0.10/milestones

  - name: csn
    base: http://crawlus.somatika.net
    logfiles:
      - scoring/crawl-trunk/logfile
      - scoring/crawl-0.11/logfile
    milestones:
      - scoring/crawl-trunk/milestones
      - scoring/crawl-0.11/milestones
