scoring-base: 'http://crawl.akrasiac.org'

sources:
  - name: cao
    base: http://crawl.akrasiac.org

    # If the file exists in this path, it will be linked into the data
    # directory from the local path; otherwise it will be fetched
    # using http.
    local: /var/www
    logfiles:
      - allgames.txt
      - logfile04
      - logfile05
      - logfile06
      - logfile07
      - logfile08
      - logfile09
      - logfile10
      - logfile11
      - logfile12
      - logfile13
      - logfile14
      - logfile15
      - logfile-git
    milestones:
      - milestones02
      - milestones03
      - milestones04
      - milestones05
      - milestones06
      - milestones07
      - milestones08
      - milestones09
      - milestones10
      - milestones11
      - milestones12
      - milestones13
      - milestones14
      - milestones15
      - milestones-git

    # Regex -> location; player name is automatically appended.
    morgues:
      - http://crawl.akrasiac.org/rawdata

  - name: cdo
    base: http://crawl.develz.org
    logfiles:
      - allgames-0.4.txt
      - allgames-0.5.txt
      - allgames-0.6.txt
      - allgames-0.7.txt
      - allgames-0.8.txt
      - allgames-0.10.txt
      - allgames-0.11.txt
      - allgames-0.12.txt
      - allgames-0.13.txt
      - allgames-0.14.txt
      - allgames-0.15.txt
      - allgames-svn.txt
    milestones:
      - milestones-0.6.txt
      - milestones-0.7.txt
      - milestones-0.8.txt
      - milestones-0.10.txt
      - milestones-0.11.txt
      - milestones-0.12.txt
      - milestones-0.13.txt
      - milestones-0.14.txt
      - milestones-0.15.txt
      - milestones-svn.txt
    morgues:
      - - time_gt: ['end_time', '20110819-1740']
          version_match: ['v', '0.9']
        - http://crawl.develz.org/morgues/0.9
      - ['cdo.*-(?:svn)', 'http://crawl.develz.org/morgues/trunk']
      - ['cdo.*-(.*)$', 'http://crawl.develz.org/morgues/$1']

  - name: cszo
    base: http://dobrazupa.org
    logfiles:
      - meta/git/logfile
      - meta/0.15/logfile
      - meta/0.14/logfile
      - meta/0.13/logfile
      - meta/0.12/logfile
      - meta/0.11/logfile
      - meta/0.10/logfile
    milestones:
      - meta/git/milestones
      - meta/0.15/milestones
      - meta/0.14/milestones
      - meta/0.13/milestones
      - meta/0.12/milestones
      - meta/0.11/milestones
      - meta/0.10/milestones
    morgues:
      - http://dobrazupa.org/morgue

  - name: clan
    base: http://crawl.lantea.net/crawl
    logfiles:
      - meta/git/logfile
      - meta/0.15/logfile
      - meta/0.14/logfile
      - meta/0.13/logfile
      - meta/0.12/logfile
      - meta/0.11/logfile
      - meta/0.10/logfile
    milestones:
      - meta/git/milestones
      - meta/0.15/milestones
      - meta/0.14/milestones
      - meta/0.13/milestones
      - meta/0.12/milestones
      - meta/0.11/milestones
      - meta/0.10/milestones
    morgues:
      - http://crawl.lantea.net/crawl/morgue

  - name: rhf
    base: http://rl.heh.fi/
    logfiles:
      - meta/crawl-git/logfile
      - meta/crawl-0.12/logfile
    milestones:
      - meta/crawl-git/milestones
      - meta/crawl-0.12/milestones
    morgues:
      - http://rl.heh.fi/morgue/

  - name: cbro
    base: http://crawl.berotato.org/crawl
    logfiles:
      - meta/git/logfile
      - meta/0.13/logfile
      - meta/0.14/logfile
      - meta/0.15/logfile
    milestones:
      - meta/git/milestones
      - meta/0.13/milestones
      - meta/0.14/milestones
      - meta/0.15/milestones
    morgues:
      - http://crawl.berotato.org/crawl/morgue/

  - name: ckr
    base: http://kr.dobrazupa.org/
    logfiles:
      - www/trunk/logfile
      - www/0.13/logfile
      - www/0.14/logfile
      - www/0.15/logfile
    milestones:
      - www/trunk/milestones
      - www/0.13/milestones
      - www/0.14/milestone
      - www/0.15/milestones
    morgues:
      - ['.*-(?:trunk|git)', 'http://kr.dobrazupa.org/morgue/trunk']
      - ['.*-([0-9]\.[0-9]+)', 'http://kr.dobrazupa.org/morgue/$1']
      - ['.*', 'http://kr.dobrazupa.org/morgue/0.13']

  - name: lld
    base: http://lazy-life.ddo.jp:8080
    logfiles:
      - meta/trunk/logfile
      - meta/0.15/logfile
      - meta/0.14/logfile
    milestones:
      - meta/trunk/milestones
      - meta/0.14/milestones
      - meta/0.15/milestones
    morgues:
      - http://lazy-life.ddo.jp:8080/morgue

  - name: cxc
    base: http://crawl.xtahua.com/crawl
    logfiles:
      - meta/git/logfile
      - meta/0.14/logfile
      - meta/0.15/logfile
    milestones:
      - meta/git/milestones
      - meta/0.14/milestones
      - meta/0.15/milestones
    morgues:
      - http://crawl.xtahua.com/crawl/morgue

  - name: cpo
    base: https://crawl.project357.org/
    logfiles:
      - dcss-logfiles-trunk
      - dcss-logfiles-0.15
    milestones:
      - dcss-milestones-trunk
      - dcss-milestones-0.15
    morgues:
      - https://crawl.project357.org/morgue

  - name: csn
    base: http://crawlus.somatika.net
    logfiles: {}
    milestones: {}
    morgues:
      - http://crawlus.somatika.net/dumps
